"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = __importDefault(require("./middleware/auth"));
const member_delete_1 = __importDefault(require("./controller/admin/member-delete"));
const admin_create_1 = __importDefault(require("./controller/admin/admin-create"));
const admin_list_1 = __importDefault(require("./controller/admin/admin-list"));
const admin_getbyid_1 = __importDefault(require("./controller/admin/admin-getbyid"));
const controller_1 = __importDefault(require("./controller/login/controller"));
const controller_2 = __importDefault(require("./controller/logout/controller"));
const controller_3 = __importDefault(require("./controller/accesstoken/controller"));
const routerv1 = (0, express_1.Router)();
routerv1.route("/login").post(controller_1.default);
routerv1.route("/logout").get(auth_1.default, controller_2.default);
routerv1.route("/accesstoken").get(controller_3.default);
routerv1.route("/admin").post(admin_create_1.default).get(admin_list_1.default);
routerv1.route("/adminById").get(admin_getbyid_1.default);
routerv1.route("/memberById/:memId").delete(auth_1.default, member_delete_1.default);
exports.default = routerv1;
